name: Docker Image CI - Rpi

on:
  push:
    tags:
      - n8n@*
  workflow_dispatch:
    inputs:
      version:
        description: 'n8n version to build docker image for.'
        required: true
        default: '0.112.0'

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARMv7 (Rpi)
    steps:
      - uses: actions/checkout@v1
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})

      - name: Log in to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Run Buildx (push image)
        if: success()
        run: |
          docker buildx build \
          --platform linux/arm/v7 \
          --build-arg N8N_VERSION=${{github.event.inputs.version || steps.vars.outputs.tag}} \
          -t ${{ secrets.DOCKER_USERNAME }}/n8n:${{github.event.inputs.version || steps.vars.outputs.tag}}-rpi \
          -t ${{ secrets.DOCKER_USERNAME }}/n8n:latest-rpi \
          --output type=image,push=true docker/images/n8n-rpi
